### ISSUE TITLE
[Feature] Migrate the Doubt Engine page to tailwind as a subtask for converting all the pages to tailwind assigned to me

### ISSUE THREAD

**Issue by jiteshpahwa04** [JAYESHBATRA/Virtuo-Learn#79]
### Description

Currently CSS is being used in the codebase. The company wants to migrate to Tailwind CSS. Separate pull requests will be made for each section that is converted.
Please assign this to me so that I can create the pull request.

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor
